### ISSUE TITLE
Feedback sobre a iteração1

### ISSUE THREAD

**Issue by lsca** [IF977/VivaRecife#25]
Eai pessoal, beleza??

Tive uma duvida no postmortem de vocês!

Criação de issues | @gbl3 @jgnvs @jwmrf @caroolpmelo | | Começar desenvolvimento do sistema | @gbl3 @jwmrf @caroolpmelo 

@jgnvs  Não vai participar do desenvolvimento do sistema?
Outra duvida, a criação de issues é feita por todos vocês? 
Nada não foi feito? O preenchimento do campo é obrigatório, você tem que documentar que nada não foi feito. 

Ex:

> ## O que não foi feito
> Nada não foi feito. Concluímos a iteração com êxito.

Espero a resposta de vocês para dar a nota da IT1 sobre o postmortem. Até o momento: 

O que estava planejado -> Valia 2, tirou 2.
O que foi feito -> Valia 2, tirou 2.
O que não foi feito -> Valia 2, tirou 0.
O que está planejado pra próxima iteração ->  Valia 2, tirou 2.
Lições aprendidas -> Valia 2, tirou 2.

Vlw!

**Comment by ghost** [comment]
Vou participar sim, teve algumas problemas pessoais que já resolvi.

Em 16 de out de 2017 2:37 PM, "lsca" <notifications@github.com> escreveu:

**Comment by caroolpmelo** [comment]
As criações de issues são feitas por todos

**Comment by lsca** [comment]
Pronto pessoal, nota colocada lá.

Qualquer duvida só falar aqui. Caso contrario, só fechar a issue.

Vlw!

**Comment by caroolpmelo** [comment]
@lsca fiz uma alteração no Postmortem sobre o que não foi feito, dá uma olhada, era a info do 'status' da iteração que estava faltando?

**Comment by lsca** [comment]
Peguei o ultimo commit do dia 9 e dei "browse files". O commit mostra o "O que não foi feito" com nada escrito. Mas com o commit do dia 11 ta tudo OK!
