### ISSUE TITLE
Correção Postmortem i2

### ISSUE THREAD

**Issue by SandrineMartins** [IF977/VivaRecife#40]
Não encontrei o postmortem da iteração 2

### Nota Final -> 0

**Comment by jwmrf** [comment]
Oi, tivemos um problema em relação ao postmortem, caso haja tempo de
reavaliar, ele já está no repositório.

Em 25/10/2017 16:33, "Sandrine" <notifications@github.com> escreveu:

**Comment by SandrineMartins** [comment]
@jwmrf não chegou notificação pra mim da tua resposta, por isso não respondi antes, mas de qualquer forma não haveria possibilidade de reavaliação pq o tempo de entrega já havia passado.

**Comment by caroolpmelo** [comment]
@SandrineMartins mas entregas atrasadas recebem pontuação, só que com redução de nota, não era assim não?

**Comment by SandrineMartins** [comment]
@caroolpmelo entregas com no máximo 2 dias de atraso tem a pontuação reduzida, a partir do 3 dia a nota é 0

**Comment by SandrineMartins** [comment]
@caroolpmelo o postmortem da i2 de vocês foi postado dia 03/11, a i2 acabou dia 23/10

**Comment by SandrineMartins** [comment]
@caroolpmelo erro meu, confundi as datas. Vou atualizar a nota.

**Comment by caroolpmelo** [comment]
Ahh okay, obrigada! 😄
